"""empty message

Revision ID: 2b7bc57ed324
Revises: c706fb380757
Create Date: 2018-10-16 16:29:17.092605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b7bc57ed324'
down_revision = 'c706fb380757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('display_email_flag', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('display_name_flag', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('display_phone_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'display_phone_flag')
    op.drop_column('users', 'display_name_flag')
    op.drop_column('users', 'display_email_flag')
    # ### end Alembic commands ###
