"""empty message

Revision ID: 2da75fc0fdd8
Revises: efa51de53f0a
Create Date: 2018-11-21 10:39:14.669362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da75fc0fdd8'
down_revision = 'efa51de53f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_count', sa.Integer(), nullable=True))
    op.drop_index('ix_users_telephone', table_name='users')
    op.create_index(op.f('ix_users_telephone'), 'users', ['telephone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telephone'), table_name='users')
    op.create_index('ix_users_telephone', 'users', ['telephone'], unique=True)
    op.drop_column('users', 'login_count')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###
