"""empty message

Revision ID: 301ed8345d87
Revises: d088a87e8b88
Create Date: 2018-09-29 22:34:33.581298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '301ed8345d87'
down_revision = 'd088a87e8b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('status', sa.Column('default_for_domain', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'default_for_domain')
    # ### end Alembic commands ###
