"""empty message

Revision ID: 516cb730ee62
Revises: d886ccaad269
Create Date: 2018-10-09 09:51:51.919081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '516cb730ee62'
down_revision = 'd886ccaad269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company_confirmed')
    # ### end Alembic commands ###
