"""empty message

Revision ID: 5c1b3a81305e
Revises: de2c3897b884
Create Date: 2018-11-10 08:59:55.818139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c1b3a81305e'
down_revision = 'de2c3897b884'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('admin_notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'admin_notes')
    # ### end Alembic commands ###
