"""empty message

Revision ID: 67a39b381c32
Revises: 0737cd165045
Create Date: 2018-10-04 13:25:24.769437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67a39b381c32'
down_revision = '0737cd165045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmation_token', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmation_token')
    # ### end Alembic commands ###
