"""empty message

Revision ID: 76e53bf2dfd4
Revises: 8496fffe78fc
Create Date: 2018-10-05 09:53:11.920372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76e53bf2dfd4'
down_revision = '8496fffe78fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transition', sa.Column('admin_only', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transition', 'admin_only')
    # ### end Alembic commands ###
