"""empty message

Revision ID: b742cb3af15e
Revises: cf1a4e30734d
Create Date: 2018-11-30 00:07:37.826778

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b742cb3af15e'
down_revision = 'cf1a4e30734d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('status', 'css_class')
    op.add_column('team_member', sa.Column('project_manager', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team_member', 'project_manager')
    op.add_column('status', sa.Column('css_class', mysql.VARCHAR(length=10), nullable=False))
    # ### end Alembic commands ###
