"""empty message

Revision ID: c5a464afbb3e
Revises: 061f935d05e8
Create Date: 2018-09-29 19:30:35.770759

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5a464afbb3e'
down_revision = '061f935d05e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('last_notification_check', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_table('admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('last_notification_check', mysql.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    # ### end Alembic commands ###
