"""empty message

Revision ID: c706fb380757
Revises: 516cb730ee62
Create Date: 2018-10-11 09:37:03.788508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c706fb380757'
down_revision = '516cb730ee62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='company')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('name', 'company', ['name'], unique=True)
    # ### end Alembic commands ###
