"""empty message

Revision ID: d088a87e8b88
Revises: c5a464afbb3e
Create Date: 2018-09-29 19:58:32.646287

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd088a87e8b88'
down_revision = 'c5a464afbb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('name', sa.String(length=30), nullable=False))
    op.drop_column('domain', 'domain')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domain', sa.Column('domain', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('domain', 'name')
    # ### end Alembic commands ###
