"""empty message

Revision ID: d1998f22f25f
Revises: 2eaba3ac57e4
Create Date: 2018-10-08 22:32:38.851275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd1998f22f25f'
down_revision = '2eaba3ac57e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('accident_procedure_flag', sa.Boolean(), nullable=True))
    op.drop_column('company', 'accident_policy_flag')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('accident_policy_flag', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('company', 'accident_procedure_flag')
    # ### end Alembic commands ###
