"""empty message

Revision ID: e400ad600354
Revises: 2b7bc57ed324
Create Date: 2018-10-30 15:40:17.845379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e400ad600354'
down_revision = '2b7bc57ed324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('online_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'online_flag')
    # ### end Alembic commands ###
